version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    name: minio
    restart: always
    ports:
      - ${MINIO_API_PORT}:${MINIO_API_PORT}
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_STORAGE_USE_HTTPS: ${MINIO_STORAGE_USE_HTTPS}
      MINIO_API_PORT: ${MINIO_API_PORT}
      MINIO_CONSOLE_PORT: ${MINIO_CONSOLE_PORT}
    volumes:
      - miniodata:/data
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_API_PORT}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
 
volumes:
  miniodata: